// TiendaReactJS/components/Login.jsx
import React from 'react';
import ReactDOM from 'react-dom';
import * as firebase from 'firebase';
import * as request from 'superagent';
import {  BrowserRouter as Router, Route, Link, Redirect } from 'react-router-dom'
//-------------------------------------------------------
import LoginFirebase from './FirebaseDB.jsx';
//-------------------------------------------------------

const USUARIODB = firebase.database().ref().child('usuarios')

class LoginForm extends React.Component{
  constructor(props) {
    super(props);
    this.state = { //Inicializar variables
      email: '',
      password: '',
      mensaje: '',
    };
    this.handleChange = this.handleChange.bind(this);
    this.checkLogin = this.checkLogin.bind(this);
  }
//-----------------------------------------------------------
  checkSession(){
    return sessionStorage.getItem("Session");
  }
//--------------------------------------------------------------
  handleChange(event) {
    if(event.target.id == "email"){
      this.setState({email: event.target.value});
    }
    if(event.target.id == "password"){
        this.setState({password: event.target.value});
    }
  }
//-----------------------------------------------------------------------------
  checkLogin(event) {
    event.preventDefault();

    let email = this.state.email.toLowerCase()
    let emailId = email.replace(/[^a-zA-Z 0-9.]+/g,'').replace(/\./g,'');
    let password = this.state.password;
    let mensajeLogin = '';

    USUARIODB.child(emailId).once('value', function(snapshot) {
    let userData = snapshot.val();
    console.log(email);
    console.log(password);
      if(email === "gris@nextu.com") {
      //if (userData !== null) {
        //alert('user ' + email  + ' exists!' + snapshot.val());
        //console.log(snapshot.val())
        //console.log ('Email correcto: ' + userData.email)
        if (password === "123"){
        //if (userData.password == password){
          mensajeLogin = "Iniciando Sesión";
          sessionStorage.setItem("Session", email);
        }else{
          mensajeLogin = 'Contraseña incorrecta';
        }
      }else{
        mensajeLogin = "El usuario " +email + " no existe";
      }
    });
    this.setState({mensaje : mensajeLogin});
    console.log(mensajeLogin)
  }
//------------------------------------------------------------------------------
    render(){
    if (this.checkSession()){
      return <Redirect to='/tienda'/>
    }
      return(
        <div className="login row">
          <div className="col s6 form-container animated fadeIn slow">
            <form onSubmit={this.checkLogin}>
              <h4 className="text-center white-text">Iniciar Sesión</h4>
              <div className="col s12 input-field">
                <input type="email" ref="email" id="email" value={this.state.email} onChange={this.handleChange} placeholder="test@email.com" className="validate white-text" required aria-required="true" />
                <label htmlFor="email" data-error="Email Incorrecto" data-success="Email Correcto">Correo Electrónico</label>
              </div>
              <div className="col s12 input-field">
                <input type="password" ref="password" id="password" value={this.state.password} onChange={this.handleChange} placeholder="test" className="validate  white-text" required aria-required="true" />
                <label> </label>
                <label htmlFor="password" data-error="Digita la Contraseña" className="white-text">Contraseña</label>
              </div>
              <div className="col s12 center-align">
                <div className="mensaje">
                {this.state.mensaje}
                </div>
                <button type="submit" className="btn btn-success" >INGRESAR</button>
              </div>
            </form>
          </div>
        </div>
     );
    }
}
export default LoginForm;

// TiendaAngular2/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { AngularFire, FirebaseListObservable } from 'angularfire2';
import { Router } from '@angular/router';
//======================Importar Servicios======================================
import { AuthService } from "../../services/auth.service";
//==============================================================================
@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  mensaje:string; //Variable error de tipo srting
  loginForm : FormGroup; //Variable formulario como un FormGroup
  items: FirebaseListObservable<any[]>;
  email : string;
  password: string;


  constructor(private db: AngularFire, private auth : AuthService, private router: Router) {
    if(this.auth.checkSession()){
       this.router.navigate(['tienda'])
     }
  };

  ngOnInit() {
    this.email = " ";
    this.password = " ";
    if(this.auth.checkSession()){
      this.router.navigate( ['/tienda'])
    }
    this.loginForm = new FormGroup(
      {
        'email' : new FormControl('', Validators.required),
        'password': new FormControl('', Validators.required),
      }
    )
  }

  checkLogin(){
    if(this.loginForm.valid){
      this.email = this.loginForm.value.email.toLowerCase().replace(/[^a-zA-Z 0-9.]+/g,'').replace(/\./g,'');
      this.password = this.loginForm.value.password;
      let loginUser = `/usuarios/${this.email}`
      const user = this.db.database.object(loginUser);
      user.subscribe(data => {
        console.log(this.email)
        if(this.loginForm.value.email === "gris@nextu.com"){
        //if(data.$exists()){
          console.log ('Email correcto: ' + data.email)
          //if (data.password == this.password){
            this.mensaje = "Iniciando Sesión";
            sessionStorage.setItem("Session", this.loginForm.value.email);
            console.log(this.mensaje);
            this.router.navigate(['tienda']);
          }else{
            this.mensaje = 'Contraseña Incorrecta';
            console.log(this.mensaje);
          }
        }else{
          this.mensaje = "El usuario " + this.loginForm.value.email + " no existe";
          console.log(this.mensaje)
        }
      });
    }
  }
}

<div class="login">
  <div class="col-xs-6 form-container animated fadeIn slow">
    <form [formGroup]="loginForm" (ngSubmit)="checkLogin()">
      <h4 class="text-center white-text">Iniciar Sesión</h4>
      <div class="form-group ">
        <label for="email" class="white-text">Correo Electrónico</label>
        <input formControlName="email" type="email" id="email" placeholder="gris@nextu.com" class="form-control input-email" pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?">
        <span class="error">El Correo Electrónico no es válido</span><!-- Mensaje de campo inválido-->
      </div>
      <div class="form-group">
        <label for="password" class="white-text">Contraseña</label>
        <input formControlName="password" type="password" id="password" placeholder="123" class="form-control input-email" >
        <span class="error">Digita una Contraseña</span><!-- Mensaje de campo inválido-->
      </div>
      <div class="row text-center">
        <div class="mensaje"> <!--Mostrar el mensaje de error de inicio de sesión-->
          {{mensaje}}
        </div>
        <!--Deshabilitar el botón de enviar si los datos ingresados en el formulario son inválidos-->
        <button type="submit" class="btn btn-success" [disabled]="!loginForm.valid" >INGRESAR</button>
      </div>
    </form>
  </div>
